### ISSUE TITLE
Multiple version compare

### ISSUE THREAD

**Issue by Rohit-peerbits** [Xiphe/jQuery-Merge-for-php-diff#8]
How can i use multiple version compare and merge feature on same page?

**Comment by Xiphe** [comment]
This should be achievable by using a more specific selectors for the different versions. 

```js
$('#diff1 .Differences').phpdiffmerge(/* ... */);
$('#diff2 .Differences').phpdiffmerge(/* ... */);
```

That said, I have not maintained this for long and currently plan to do a complete rewrite within the next months. I'll ensure that future versions will support this.

**Comment by Rohit-peerbits** [comment]
Hey @Xiphe , Thanks a lot for your response :+1:
